name: Build JAR

on:
  push:
    branches: [ "main" ]   # (a) dispara em push para a branch principal
  workflow_dispatch:        # permite correr manualmente se precisares

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21 (Temurin)   # (b) Java 21+
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Compilar e empacotar (Maven)   # (c) mvn clean package
        run: mvn -B clean package

      - name: Publicar artefacto (.jar)      # (d) publicar o .jar
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          if-no-files-found: error
